// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Article: typeof import('./components/common/typography/Article.vue')['default']
    Button: typeof import('./components/common/button/Button.vue')['default']
    Footer: typeof import('./components/layout/layout/Footer.vue')['default']
    Header: typeof import('./components/layout/layout/Header.vue')['default']
    Logo: typeof import('./components/common/logo/Logo.vue')['default']
    Paragraph: typeof import('./components/common/typography/Paragraph.vue')['default']
    PopupMenu: typeof import('./components/common/popup-menu/PopupMenu.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Score: typeof import('./components/common/score/Score.vue')['default']
    SelectField: typeof import('./components/common/select-field/SelectField.vue')['default']
    SplashScreen: typeof import('./components/layout/layout/SplashScreen.vue')['default']
    Tooltip: typeof import('./components/common/tooltip/Tooltip.vue')['default']
  }
}
